#
# DoubleConversion
#

SET(DOUBLECONVERSION_TARGET "DoubleConversion-1.1.5")

SET(DOUBLECONVERSION_REPOSITORY_TARGET "${DOUBLECONVERSION_TARGET}-Repository")
ExternalProject_Add(${DOUBLECONVERSION_REPOSITORY_TARGET}
    GIT_REPOSITORY "https://github.com/google/double-conversion.git"
    GIT_TAG "v1.1.5"
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND "")
ExternalProject_Get_Property(${DOUBLECONVERSION_REPOSITORY_TARGET} SOURCE_DIR)
SET(DOUBLECONVERSION_REPOSITORY_SOURCE_DIR ${SOURCE_DIR})
FILE(MAKE_DIRECTORY "${DOUBLECONVERSION_REPOSITORY_SOURCE_DIR}")
FILE(WRITE "${DOUBLECONVERSION_REPOSITORY_SOURCE_DIR}/.ignore")

#
IF(MSVC)
    SET(DOUBLECONVERSION_WIN64_VS2012_OPTIONS "${PLATFORM_WIN64_VS2012}" "${GENERATOR_VS2012_WIN64}")
    SET(DOUBLECONVERSION_WIN64_VS2015_OPTIONS "${PLATFORM_WIN64_VS2015}" "${GENERATOR_VS2015_WIN64}")
    FOREACH(OPTIONS "${DOUBLECONVERSION_WIN64_VS2012_OPTIONS}" "${DOUBLECONVERSION_WIN64_VS2015_OPTIONS}")
        LIST(GET OPTIONS 0 PLATFORM)
        LIST(GET OPTIONS 1 GENERATOR)

        #
        FOREACH(CONFIGURATION_TYPE ${CMAKE_CONFIGURATION_TYPES})
            SET(INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/${PLATFORM}/${CONFIGURATION_TYPE}/${DOUBLECONVERSION_TARGET}")
            SET(CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}")

            SET(DOUBLECONVERSION_INSTALL_TARGET "${DOUBLECONVERSION_TARGET}-${PLATFORM}-${CONFIGURATION_TYPE}")
            MESSAGE(${DOUBLECONVERSION_INSTALL_TARGET})

            ExternalProject_Add(${DOUBLECONVERSION_INSTALL_TARGET}
                DEPENDS ${DOUBLECONVERSION_REPOSITORY_TARGET}
                SOURCE_DIR ${DOUBLECONVERSION_REPOSITORY_SOURCE_DIR}
                CMAKE_ARGS ${CMAKE_ARGS}
                CMAKE_CACHED_ARGS "-DCMAKE_CONFIGURATION_TYPES=${CONFIGURATION_TYPE}"
                BUILD_COMMAND "${CMAKE_COMMAND}" --build . --config ${CONFIGURATION_TYPE} --target INSTALL
                INSTALL_DIR ${INSTALL_DIR})
        ENDFOREACH()
    ENDFOREACH()
ELSEIF(APPLE)
    # TODO: OSX
ELSE()
    # TODO: Linux
ENDIF()
