#
# GLEW 2.0.0
#

SET(GLEW_TARGET "GLEW-2.0.0")

SET(GLEW_DOWNLOAD_TARGET "${GLEW_TARGET}-Download")
ExternalProject_Add(${GLEW_DOWNLOAD_TARGET}
    URL "http://downloads.sourceforge.net/project/glew/glew/2.0.0/glew-2.0.0.tgz"
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND "")
ExternalProject_Get_Property(${GLEW_DOWNLOAD_TARGET} SOURCE_DIR)
SET(GLEW_DOWNLOAD_SOURCE_DIR ${SOURCE_DIR})
FILE(MAKE_DIRECTORY "${GLEW_DOWNLOAD_TARGET}/build/cmake")
FILE(WRITE "${GLEW_DOWNLOAD_TARGET}/build/cmake/.ignore")

IF(MSVC)
    SET(GLEW_WIN64_VS2012_OPTIONS "${PLATFORM_WIN64_VS2012}" "${GENERATOR_VS2012_WIN64}")
    SET(GLEW_WIN64_VS2015_OPTIONS "${PLATFORM_WIN64_VS2015}" "${GENERATOR_VS2015_WIN64}")

    FOREACH(OPTIONS "${GLEW_WIN64_VS2012_OPTIONS}" "${GLEW_WIN64_VS2015_OPTIONS}")
        LIST(GET OPTIONS 0 PLATFORM)
        LIST(GET OPTIONS 1 GENERATOR)

        #
        FOREACH(CONFIGURATION_TYPE ${CMAKE_CONFIGURATION_TYPES})
            SET(INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/${PLATFORM}/${CONFIGURATION_TYPE}/${GLEW_TARGET}")
            SET(CMAKE_ARGS "-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}")

            IF(${CONFIGURATION_TYPE} STREQUAL "Debug")
                LIST(APPEND CMAKE_ARGS "-DCMAKE_C_FLAGS_DEBUG=\"/D_DEBUG /MDd /Zi /Ob0 /Od\"")
            ENDIF()

            #
            SET(GLEW_INSTALL_TARGET ${GLEW_TARGET}-${PLATFORM}-${CONFIGURATION_TYPE})
            MESSAGE("${GLEW_INSTALL_TARGET} ${INSTALL_DIR}")

            ExternalProject_Add(${GLEW_INSTALL_TARGET}
                DEPENDS ${GLEW_DOWNLOAD_TARGET}
                SOURCE_DIR ${GLEW_DOWNLOAD_SOURCE_DIR}/build/cmake
                CMAKE_GENERATOR ${GENERATOR}
                CMAKE_ARGS ${CMAKE_ARGS}
                BUILD_COMMAND ${CMAKE_COMMAND} --build . --config ${CONFIGURATION_TYPE} --target install
                INSTALL_DIR ${INSTALL_DIR})
        ENDFOREACH()
    ENDFOREACH()
ELSE()
ENDIF()
