#
# OpenEXR 2.2.0
#

SET(OPENEXR_TARGET "OpenEXR-2.2.0")

SET(OPENEXR_REPOSITORY_TARGET "${OPENEXR_TARGET}-Repository")
ExternalProject_Add(${OPENEXR_REPOSITORY_TARGET}
    GIT_REPOSITORY "https://github.com/openexr/openexr"
    GIT_TAG "v2.2.0"
    CONFIGURE_COMMAND ""
    BUILD_COMMAND ""
    INSTALL_COMMAND "")
ExternalProject_Get_Property(${OPENEXR_REPOSITORY_TARGET} SOURCE_DIR)
SET(OPENEXR_REPOSITORY_SOURCE_DIR ${SOURCE_DIR})
FILE(MAKE_DIRECTORY "${OPENEXR_REPOSITORY_SOURCE_DIR}/IlmBase")
FILE(WRITE "${OPENEXR_REPOSITORY_SOURCE_DIR}/IlmBase/.ignore")

IF(MSVC)
    SET(OPENEXR_WIN64_VS2012_OPTIONS "${PLATFORM_WIN64_VS2012}" "${GENERATOR_VS2012_WIN64}")
    SET(OPENEXR_WIN64_VS2015_OPTIONS "${PLATFORM_WIN64_VS2015}" "${GENERATOR_VS2015_WIN64}")

    FOREACH(OPTIONS "${OPENEXR_WIN64_VS2012_OPTIONS}" "${OPENEXR_WIN64_VS2015_OPTIONS}")
        LIST(GET OPTIONS 0 PLATFORM)
        LIST(GET OPTIONS 1 GENERATOR)

        #
        FOREACH(CONFIGURATION_TYPE ${CMAKE_CONFIGURATION_TYPES})
            SET(INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/${PLATFORM}/${CONFIGURATION_TYPE}/${OPENEXR_TARGET}")
            SET(CMAKE_ARGS "-DBUILD_SHARED_LIBS=0" "-DCMAKE_INSTALL_PREFIX=${INSTALL_DIR}")

            SET(OPENEXR_INSTALL_TARGET ${OPENEXR_TARGET}-${PLATFORM}-${CONFIGURATION_TYPE})
            MESSAGE(${OPENEXR_INSTALL_TARGET})

            ExternalProject_Add(${OPENEXR_INSTALL_TARGET}
                DEPENDS ${OPENEXR_REPOSITORY_TARGET}
                SOURCE_DIR ${OPENEXR_REPOSITORY_SOURCE_DIR}/IlmBase
                CMAKE_GENERATOR ${GENERATOR}
                CMAKE_ARGS ${CMAKE_ARGS}
                BUILD_COMMAND ${CMAKE_COMMAND} --build . --config ${CONFIGURATION_TYPE} --target install
                INSTALL_DIR ${INSTALL_DIR})
        ENDFOREACH()
    ENDFOREACH()
ELSEIF(APPLE)
ELSE()
ENDIF()
